add docs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,7 +22,7 @@ jobs:
           python-version: ${{ matrix.python-version }}
       - name: Install Python dependencies
         run: |
-          uv pip install -e ".[dev]" --system
+          uv pip install -e ".[dev,docs]" --system
       - name: Run tests with coverage
         run: make test
       - name: Upload coverage to Codecov
@@ -31,6 +31,23 @@ jobs:
           file: ./coverage.xml
           fail_ci_if_error: false
           verbose: true
+      - name: Test documentation builds
+        run: make documentation
+      - name: Check documentation build
+        run: |
+          for notebook in $(find docs/_build/jupyter_execute -name "*.ipynb"); do
+            if grep -q '"output_type": "error"' "$notebook"; then
+              echo "Error found in $notebook"
+              cat "$notebook"
+              exit 1
+            fi
+          done
+      - name: Deploy documentation
+        uses: JamesIves/github-pages-deploy-action@releases/v3
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BRANCH: gh-pages  # The branch the action should deploy to.
+          FOLDER: docs/_build/html  # The folder the action should deploy.
   publish-to-pypi:
     name: Publish to PyPI
     needs: Test
